import { useState } from 'react';
import { DndContext, PointerSensor, KeyboardSensor, useDraggable, useDroppable, useSensor, useSensors } from '@dnd-kit/core';
import { addDays, addMonths, endOfMonth, endOfWeek, format, parseISO, startOfMonth, startOfWeek } from 'date-fns';
import { CalendarDays, ChevronLeft, ChevronRight, GripVertical, Pencil, Trash2 } from 'lucide-react';
import { IconButton, Modal } from './components';
import type { SavedDay } from './saved-days';
import { staticSite } from './static-mode';

function DayCard({ day, busy, onEdit, onDelete, onMove }: { day: SavedDay; busy: boolean; onEdit: () => void; onDelete: () => void; onMove: () => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: day.id, disabled: busy });
  return <article ref={setNodeRef} className="calendar-card" aria-label={day.name} style={{ transform: transform ? `translate3d(${transform.x}px,${transform.y}px,0)` : undefined, zIndex: isDragging ? 10 : undefined, opacity: isDragging ? .8 : 1 }}><div className="calendar-card-heading"><h3>{day.name}</h3><button className="drag-handle" {...attributes} {...listeners} title={`Move ${day.name}`} aria-label={`Drag ${day.name} to another date`}><GripVertical size={16} /></button></div><div className="tag-list">{day.tags?.map((tag, index) => <span key={index}>{tag}</span>)}</div><p className="muted small">{day.stops.length} activities</p><div className="row"><IconButton label={`Edit ${day.name}`} disabled={busy} onClick={onEdit}><Pencil size={16} /></IconButton><IconButton label={`Reschedule ${day.name}`} disabled={busy} onClick={onMove}><CalendarDays size={16} /></IconButton><IconButton label={`Remove ${day.name}`} disabled={busy} onClick={onDelete}><Trash2 size={16} /></IconButton></div></article>;
}
function CalendarCell({ date, inMonth, children }: { date: string; inMonth: boolean; children: React.ReactNode }) {
  const { setNodeRef, isOver } = useDroppable({ id: date });
  return <div ref={setNodeRef} className={`calendar-cell ${inMonth ? '' : 'outside-month'} ${isOver ? 'drop-target' : ''}`} aria-label={date} data-date={date}><time dateTime={date}>{Number(date.slice(-2))}</time>{children}</div>;
}
type Props = { days: SavedDay[]; loading: boolean; error: string; busy: boolean; email?: string; localCount: number; importError: string; onImport: () => void; onRetry: () => void; onSignIn: () => void; onEdit: (day: SavedDay) => void; onDelete: (id: string) => Promise<void>; onUpdate: (day: SavedDay) => Promise<void> };
export function SavedCalendar(props: Props) {
  const [month, setMonth] = useState(() => startOfMonth(new Date()));
  const [action, setAction] = useState<{ kind: 'edit' | 'delete' | 'move'; day: SavedDay } | null>(null);
  const [targetDate, setTargetDate] = useState('');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [working, setWorking] = useState(false);
  const busy = props.busy || working;
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }), useSensor(KeyboardSensor));
  const start = startOfWeek(startOfMonth(month)); const end = endOfWeek(endOfMonth(month));
  const dates: Date[] = []; for (let date = start; date <= end; date = addDays(date, 1)) dates.push(date);
  async function move(day: SavedDay, date: string) {
    if (busy || date === day.date) return;
    setWorking(true); setError('');
    try { await props.onUpdate({ ...day, date }); setNotice(`${day.name} moved to ${date}. Published event dates have not changed.`); setMonth(startOfMonth(parseISO(date))); setAction(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not move this day.'); }
    finally { setWorking(false); }
  }
  return <section className="saved-calendar" aria-labelledby="saved-heading"><div className="builder-heading"><div><p className="eyebrow">Your Seattle days</p><h1 id="saved-heading">My Calendar</h1></div><a className="button" href="#my-day"><CalendarDays size={18} />Create a Day</a></div><div className="collection-account"><p className="muted small">{props.email ? `Saved to ${props.email}` : staticSite ? 'Demo site: saved days are stored in this browser only.' : 'Sign in to save days to your account.'}</p>{!props.email && !staticSite && <button className="text-button" onClick={props.onSignIn}>Sign in</button>}</div>{props.localCount > 0 && <div className="local-import"><p>{props.localCount} browser-saved days</p><button className="filter-button" disabled={busy} onClick={props.onImport}>Import to this account</button></div>}{props.importError && <p role="alert">{props.importError}</p>}
    <div className="calendar-toolbar"><div className="row"><IconButton label="Previous month" onClick={() => setMonth(value => addMonths(value, -1))}><ChevronLeft size={20} /></IconButton><h2 aria-live="polite">{format(month, 'MMMM yyyy')}</h2><IconButton label="Next month" onClick={() => setMonth(value => addMonths(value, 1))}><ChevronRight size={20} /></IconButton></div><label className="field">Go to month<input type="month" value={format(month, 'yyyy-MM')} onChange={event => { if (event.target.value) setMonth(parseISO(`${event.target.value}-01`)); }} /></label></div>
    {props.loading ? <p role="status">Loading saved days...</p> : props.error ? <div role="alert">{props.error}<button className="filter-button" onClick={props.onRetry}>Try again</button></div> : <>{!props.days.length && <h2 className="small">No saved days yet.</h2>}<DndContext sensors={sensors} onDragEnd={({ active, over }) => { const day = props.days.find(value => value.id === active.id); if (day && over && /^\d{4}-\d{2}-\d{2}$/.test(String(over.id))) void move(day, String(over.id)); }}><div className="calendar-scroll" tabIndex={0} role="region" aria-label="Saved days monthly calendar"><div className="calendar-weekdays" aria-hidden="true">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(value => <span key={value}>{value}</span>)}</div><div className="calendar-grid">{dates.map(date => { const key = format(date, 'yyyy-MM-dd'); return <CalendarCell key={key} date={key} inMonth={date.getMonth() === month.getMonth()}>{props.days.filter(day => day.date === key).map(day => <DayCard key={day.id} day={day} busy={busy} onEdit={() => { setError(''); setAction({ kind: 'edit', day }); }} onDelete={() => { setError(''); setAction({ kind: 'delete', day }); }} onMove={() => { setError(''); setTargetDate(day.date); setAction({ kind: 'move', day }); }} />)}</CalendarCell>; })}</div></div></DndContext><div className="saved-agenda"><h2>All saved days</h2>{[...props.days].sort((first, second) => first.date.localeCompare(second.date)).map(day => <div className="agenda-row" key={day.id}><time>{day.date}</time><strong>{day.name}</strong><button className="text-button" onClick={() => setMonth(startOfMonth(parseISO(day.date)))}>Show on calendar</button></div>)}</div></>}
    <div className="agenda-actions" role="group" aria-label="Saved day actions">{props.days.map(day => <div className="agenda-row" key={day.id}><strong>{day.name}</strong><div className="row"><IconButton label={`Edit saved day ${day.name}`} disabled={busy} onClick={() => { setError(''); setAction({ kind: 'edit', day }); }}><Pencil size={17} /></IconButton><IconButton label={`Change date for ${day.name}`} disabled={busy} onClick={() => { setError(''); setTargetDate(day.date); setAction({ kind: 'move', day }); }}><CalendarDays size={17} /></IconButton><IconButton label={`Delete saved day ${day.name}`} disabled={busy} onClick={() => { setError(''); setAction({ kind: 'delete', day }); }}><Trash2 size={17} /></IconButton></div></div>)}</div>
    {notice && <p role="status">{notice}</p>}{error && !action && <p role="alert">{error}</p>}
    <Modal title={action?.kind === 'move' ? 'Reschedule day' : action?.kind === 'delete' ? 'Remove saved day?' : 'Edit saved day?'} open={!!action} onClose={() => { if (!busy) setAction(null); }}>{action && <><p>{action.day.name}</p>{action.kind === 'move' ? <label className="field">New date<input type="date" value={targetDate} onChange={event => setTargetDate(event.target.value)} /></label> : <p>{action.kind === 'edit' ? 'Replace the current working draft with this saved day? Changes are stored when you save.' : 'Remove this saved day? Your saved activities and working draft will remain.'}</p>}{error && <p role="alert">{error}</p>}<div className="dialog-actions"><button className="filter-button" disabled={busy} onClick={() => setAction(null)}>Cancel</button><button className="button" disabled={busy || action.kind === 'move' && (!targetDate || targetDate === action.day.date)} onClick={async () => { if (action.kind === 'move') { await move(action.day, targetDate); return; } if (action.kind === 'edit') { props.onEdit(action.day); setAction(null); return; } setWorking(true); setError(''); try { await props.onDelete(action.day.id); setAction(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not remove day.'); } finally { setWorking(false); } }}>{action.kind === 'move' ? 'Move day' : action.kind === 'edit' ? 'Edit day' : 'Remove day'}</button></div></>}</Modal>
  </section>;
}